"""Typed framework-free boundary for the RCSWX native engine."""

from collections.abc import Callable, Sequence
from typing import Self

type TokenRecord = tuple[int, str, list[str], int]
type StepRecord = tuple[int, str, int | None, int | None, int, int, float, bool, bool]
type DependencyRecord = int | list[int]
type SelectionRecord = tuple[int, float, list[DependencyRecord], list[DependencyRecord]]
type PreparedTokenRecord = tuple[str, str, list[str], int, int | None]

class NativeRng:
    def __init__(self, seed: int | bytes) -> None: ...
    @classmethod
    def from_state(cls, state: dict[str, int | str]) -> Self: ...
    def state(self) -> dict[str, int | str]: ...
    def next_u64(self) -> int: ...
    def uniform(self) -> float: ...

class NativePrepared:
    def __deepcopy__(self, memo: dict[int, object]) -> Self: ...
    @property
    def parent2_ids(self) -> list[str]: ...
    def analyze(
        self,
        plan_id: str,
        collapse_corners: bool = False,
        memory_check: Callable[[], bool] | None = None,
    ) -> NativePlan: ...
    def first_tokens(self) -> list[PreparedTokenRecord]: ...
    def second_tokens(self) -> list[PreparedTokenRecord]: ...
    def profile_json(self) -> str: ...

class NativePlan:
    def __deepcopy__(self, memo: dict[int, object]) -> Self: ...
    @property
    def id(self) -> str: ...
    @property
    def distance(self) -> float: ...
    @property
    def path_index(self) -> int: ...
    @property
    def operations(self) -> list[int]: ...
    @property
    def operations_unordered(self) -> list[int]: ...
    @property
    def nontrivial(self) -> list[int]: ...
    def stats_json(self) -> str: ...
    def selected_path_json(self) -> str: ...
    def paths_json(self) -> str: ...
    def profile_json(self) -> str: ...
    def validate_selection(self, selected: list[int]) -> None: ...
    def combinations(
        self, memory_check: Callable[[], bool] | None = None
    ) -> tuple[list[str], list[float]]: ...
    def probabilities(
        self, skewness: float, memory_check: Callable[[], bool] | None = None
    ) -> tuple[list[str], list[float], list[float]]: ...
    def sample(
        self, skewness: float, rng: NativeRng, memory_check: Callable[[], bool] | None = None
    ) -> tuple[str, float]: ...
    def apply(
        self,
        selected: list[int],
        validate: bool = True,
        memory_check: Callable[[], bool] | None = None,
    ) -> tuple[str, str, int]: ...

def validate_architecture(text: str) -> str: ...
def architecture_tokens(text: str) -> list[PreparedTokenRecord]: ...
def prepare_architectures(
    first: str,
    second: str,
    profile: bool = False,
    limits: dict[str, int | None] | None = None,
    *,
    legacy_origins: tuple[Sequence[int], Sequence[int]] | None = None,
) -> NativePrepared: ...
def native_probabilities(values: list[float], skewness: float) -> list[float]: ...
def native_draw(probabilities: list[float], rng: NativeRng) -> int: ...
def native_select(
    records: list[SelectionRecord], skewness: float, rng: NativeRng
) -> tuple[str, float]: ...
def recursive_align(
    tokens1: list[TokenRecord],
    tokens2: list[TokenRecord],
    collapse_corners: bool = False,
    memory_check: Callable[[], bool] | None = None,
) -> tuple[float, list[list[StepRecord]], dict[str, int]]: ...
def valid_combinations(records: list[SelectionRecord]) -> tuple[list[str], list[float]]: ...
