use rcswx_core::apply::apply_traced;
use rcswx_core::architecture::{Architecture, Budget, Limits};
use rcswx_core::edit_plan::analyze_traced;
use rcswx_core::sampling::{NativeRng, sample_with_budget};
use rcswx_core::tokens::prepare;
use rcswx_core::trace::{Recorder, TraceLevel, TraceLimits};
use serde_json::{Value, json};

// This helper computes actual results. Expectations are separately checked in
// from the original serial engine and are never regenerated by tests or builds.
pub fn capture(first: &str, second: &str, collapse: bool, max_events: usize) -> Value {
    let mut check = || Ok(());
    let mut budget = Budget {
        limits: Limits::default(),
        work: 0,
        output: 0,
        allocation_bytes: 0,
        check: &mut check,
    };
    let mut recorder = Recorder::new(
        TraceLevel::Full,
        TraceLimits {
            max_events,
            ..TraceLimits::default()
        },
    );
    let result = prepare(
        Architecture::from_json(first).unwrap(),
        Architecture::from_json(second).unwrap(),
    )
    .and_then(|prepared| {
        analyze_traced(
            prepared,
            collapse,
            "frozen-oracle".into(),
            &mut budget,
            &mut recorder,
        )
    });
    let analysis = match result {
        Err(error) => json!({"error":format!("{error:?}")}),
        Ok(plan) => {
            let mut stats = plan.stats.clone();
            // This is physical payload accounting, not portable algorithm work.
            stats.remove("allocation_bytes");
            let mut frames = Vec::new();
            for count in 0..=plan.operations.len() {
                let mut frame_plan = plan.clone();
                let mut frame_trace = Recorder::new(TraceLevel::Full, TraceLimits::default());
                let selected = &plan.operations[..count];
                let result = match apply_traced(
                    &mut frame_plan,
                    selected,
                    false,
                    &mut budget,
                    &mut frame_trace,
                ) {
                    Ok(applied) => {
                        json!({"architecture": applied.result.architecture.to_json().unwrap(), "origins":applied.origins})
                    }
                    Err(error) => json!({"error":format!("{error:?}")}),
                };
                frames.push(
                    json!({"selected":selected,"result":result,"trace":frame_trace.finish()}),
                );
            }
            let mut samples = Vec::new();
            for seed in [0_u8, 42, 255] {
                let mut rng = NativeRng::from_seed([seed; 32]);
                let sampled = plan
                    .selection_operations()
                    .and_then(|ops| sample_with_budget(&ops, 0.0, &mut rng, &mut budget));
                let result = match sampled {
                    Ok((mask, value)) => json!({"mask":mask,"value_bits":value.to_bits()}),
                    Err(error) => json!({"error":format!("{error:?}")}),
                };
                let state = rng.state();
                samples.push(json!({"seed":seed,"result":result,"rng":{"version":state.version,"algorithm":state.algorithm,"seed":state.seed,"stream":state.stream,"word_position":state.word_position}}));
            }
            json!({"distance_bits":plan.distance.to_bits(),"paths":plan.paths,"path_index":plan.path_index,"operations":plan.operations,"operations_unordered":plan.operations_unordered,"nontrivial":plan.nontrivial,"stats":stats,"frames":frames,"samples":samples})
        }
    };
    json!({"analysis":analysis,"trace":recorder.finish()})
}
